### PR TITLE
Do not merge: Edits for Test the Python ncclient Library from Your Computer to the Sandbox

### PR DESCRIPTION
**Pull request by annegentle**
I have a couple of questions on this. 

When I test the instructions from my Mac, I get an RPC error. Can you think of a cause?

```
ncclient.operations.rpc.RPCError: /oc-acl:acl/acl-sets/acl-set{LIST oc-acl:ACL_IPV4}/acl-entries/acl-entry{10}/ipv4/config/protocol: Unsupported IP Protocol Type
```
Also, I'm not sure why `3.md` explains how to use a Python3 virtual env but `5.md` does not comment on the use of Python3. Is that intentional?

### CODE REVIEW

**Comment by WendellOdom** [comment]
All changes approved. On Your two questions...
1) I don't know why you're getting that error, but I can recreate it. I'll take it as a todo. Something's changed since I last tested this lab about 2 months ago, but in the time I had to test this AM, I have verified that the issue is NOT with the text, but with either the code or the device config. So, you can move on with the copy edits from here, and I'll take the todo to investigate and fix. Thanks for noting the issue.
2) Yes, the choice to ignore the Python 2 vs 3 topic on page 5 is purposeful. It's a necessary discussion on page 3.

**Comment by WendellOdom** [comment]
I'm so sorry - I read the title after clicking merge. So sorry.

**Comment by annegentle** [comment]
Ah, no need to apologize, I simply wanted more investigation since I didn't consider the content technically accurate and that's the higher purpose to me. :)

**Comment by annegentle** [comment]
I'm getting similar RPC errors when using SSH, for what it's worth. Thanks for looking into it.

**Pull request merged**
